# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 635)
        self.train = QtWidgets.QWidget(MainWindow)
        self.train.setObjectName("train")
        self.groupBox = QtWidgets.QGroupBox(self.train)
        self.groupBox.setGeometry(QtCore.QRect(6, 6, 1115, 352))
        self.groupBox.setMinimumSize(QtCore.QSize(0, 82))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.settings = QtWidgets.QGroupBox(self.groupBox)
        self.settings.setTitle("")
        self.settings.setObjectName("settings")
        self.gridLayout = QtWidgets.QGridLayout(self.settings)
        self.gridLayout.setObjectName("gridLayout")
        self.reset = QtWidgets.QPushButton(self.settings)
        self.reset.setObjectName("reset")
        self.gridLayout.addWidget(self.reset, 4, 6, 1, 2)
        self.lramnt = QtWidgets.QLabel(self.settings)
        self.lramnt.setObjectName("lramnt")
        self.gridLayout.addWidget(self.lramnt, 0, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.settings)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 3, 1, 1)
        self.lrslider = QtWidgets.QSlider(self.settings)
        self.lrslider.setMinimum(1)
        self.lrslider.setMaximum(1000)
        self.lrslider.setSliderPosition(2)
        self.lrslider.setOrientation(QtCore.Qt.Horizontal)
        self.lrslider.setObjectName("lrslider")
        self.gridLayout.addWidget(self.lrslider, 0, 1, 1, 6)
        self.epocjslbl_2 = QtWidgets.QLabel(self.settings)
        self.epocjslbl_2.setObjectName("epocjslbl_2")
        self.gridLayout.addWidget(self.epocjslbl_2, 2, 0, 1, 1)
        self.sizetrainamnt = QtWidgets.QLabel(self.settings)
        self.sizetrainamnt.setObjectName("sizetrainamnt")
        self.gridLayout.addWidget(self.sizetrainamnt, 2, 7, 1, 1)
        self.epochsamnt = QtWidgets.QLabel(self.settings)
        self.epochsamnt.setObjectName("epochsamnt")
        self.gridLayout.addWidget(self.epochsamnt, 1, 7, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.settings)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.trainProgress = QtWidgets.QProgressBar(self.groupBox_2)
        self.trainProgress.setProperty("value", 0)
        self.trainProgress.setObjectName("trainProgress")
        self.gridLayout_2.addWidget(self.trainProgress, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 5, 0, 1, 8)
        self.sizetrainslider = QtWidgets.QSlider(self.settings)
        self.sizetrainslider.setMinimum(64)
        self.sizetrainslider.setMaximum(1024)
        self.sizetrainslider.setSingleStep(32)
        self.sizetrainslider.setPageStep(32)
        self.sizetrainslider.setOrientation(QtCore.Qt.Horizontal)
        self.sizetrainslider.setObjectName("sizetrainslider")
        self.gridLayout.addWidget(self.sizetrainslider, 2, 1, 1, 6)
        self.datatrainselect = QtWidgets.QPushButton(self.settings)
        self.datatrainselect.setObjectName("datatrainselect")
        self.gridLayout.addWidget(self.datatrainselect, 4, 4, 1, 1)
        self.speedlbl = QtWidgets.QLabel(self.settings)
        self.speedlbl.setObjectName("speedlbl")
        self.gridLayout.addWidget(self.speedlbl, 0, 0, 1, 1)
        self.epocjslbl = QtWidgets.QLabel(self.settings)
        self.epocjslbl.setObjectName("epocjslbl")
        self.gridLayout.addWidget(self.epocjslbl, 1, 0, 1, 1)
        self.epochsslider = QtWidgets.QSlider(self.settings)
        self.epochsslider.setMinimum(10)
        self.epochsslider.setMaximum(500)
        self.epochsslider.setOrientation(QtCore.Qt.Horizontal)
        self.epochsslider.setObjectName("epochsslider")
        self.gridLayout.addWidget(self.epochsslider, 1, 1, 1, 6)
        self.gridLayout_4.addWidget(self.settings, 0, 0, 1, 1)
        self.starttrainbtn = QtWidgets.QPushButton(self.groupBox)
        self.starttrainbtn.setObjectName("starttrainbtn")
        self.gridLayout_4.addWidget(self.starttrainbtn, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.train)
        self.groupBox_3.setGeometry(QtCore.QRect(6, 360, 1115, 271))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 6, 1, 1)
        self.sizegenslider = QtWidgets.QSlider(self.groupBox_3)
        self.sizegenslider.setMinimum(64)
        self.sizegenslider.setMaximum(2048)
        self.sizegenslider.setOrientation(QtCore.Qt.Horizontal)
        self.sizegenslider.setObjectName("sizegenslider")
        self.gridLayout_3.addWidget(self.sizegenslider, 1, 1, 1, 7)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.genProgress = QtWidgets.QProgressBar(self.groupBox_4)
        self.genProgress.setGeometry(QtCore.QRect(10, 50, 1071, 23))
        self.genProgress.setProperty("value", 0)
        self.genProgress.setObjectName("genProgress")
        self.gridLayout_3.addWidget(self.groupBox_4, 2, 0, 1, 9)
        self.datagenselect = QtWidgets.QPushButton(self.groupBox_3)
        self.datagenselect.setObjectName("datagenselect")
        self.gridLayout_3.addWidget(self.datagenselect, 0, 1, 1, 1)
        self.sizegenamnt = QtWidgets.QLabel(self.groupBox_3)
        self.sizegenamnt.setObjectName("sizegenamnt")
        self.gridLayout_3.addWidget(self.sizegenamnt, 1, 8, 1, 1)
        self.ytoxselectbtn = QtWidgets.QPushButton(self.groupBox_3)
        self.ytoxselectbtn.setObjectName("ytoxselectbtn")
        self.gridLayout_3.addWidget(self.ytoxselectbtn, 0, 7, 1, 2)
        self.startgenbtn = QtWidgets.QPushButton(self.groupBox_3)
        self.startgenbtn.setObjectName("startgenbtn")
        self.gridLayout_3.addWidget(self.startgenbtn, 3, 0, 1, 9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 2, 1, 1)
        self.xtoyselectbtn = QtWidgets.QPushButton(self.groupBox_3)
        self.xtoyselectbtn.setObjectName("xtoyselectbtn")
        self.gridLayout_3.addWidget(self.xtoyselectbtn, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 5, 1, 1)
        MainWindow.setCentralWidget(self.train)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CycleGAN"))
        self.groupBox.setTitle(_translate("MainWindow", "Тренировка"))
        self.reset.setText(_translate("MainWindow", "Сбросить"))
        self.lramnt.setText(_translate("MainWindow", "0.0002"))
        self.label.setText(_translate("MainWindow", "Dataset:"))
        self.epocjslbl_2.setText(_translate("MainWindow", "Размер"))
        self.sizetrainamnt.setText(_translate("MainWindow", "128px"))
        self.epochsamnt.setText(_translate("MainWindow", "100"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Прогресс"))
        self.datatrainselect.setText(_translate("MainWindow", "Выбрать Папку"))
        self.speedlbl.setText(_translate("MainWindow", "Скорость"))
        self.epocjslbl.setText(_translate("MainWindow", "Эпохи"))
        self.starttrainbtn.setText(_translate("MainWindow", "Start Train"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Генерация"))
        self.label_2.setText(_translate("MainWindow", "Dataset:"))
        self.label_6.setText(_translate("MainWindow", "YtoX:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Прогресс"))
        self.datagenselect.setText(_translate("MainWindow", "Выбрать Папку"))
        self.sizegenamnt.setText(_translate("MainWindow", "256px"))
        self.ytoxselectbtn.setText(_translate("MainWindow", "Выбрать Файл"))
        self.startgenbtn.setText(_translate("MainWindow", "Start Gen"))
        self.xtoyselectbtn.setText(_translate("MainWindow", "Выбрать Файл"))
        self.label_3.setText(_translate("MainWindow", "Размер:"))
        self.label_5.setText(_translate("MainWindow", "XtoY:"))

